### ISSUE TITLE
switch to io-redis to be able to work with redis-sentinel

### ISSUE THREAD

**Issue by Loki-Afro** [yjs/y-redis#28]
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[ ] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
We want to run redis as a cluster using sentinel as far as i know only the io-redis library supports redis sentinel, it also has a retry mechanism which i'm keen to use

**Describe the solution you'd like**
use io-redis instead of basic redis library

**Describe alternatives you've considered**
none

* [ ] I'm a sponsor 💖
* [x] This feature is critical for my project.

**Comment by Loki-Afro** [comment]
i'm / we are happy to create a pr @dmonad

**Comment by Loki-Afro** [comment]
hey @dmonad we replaced node-redis with io-redis in order to get it work with redis sentinel or valkey for that matter.

we would be happy to create a pr with this along some other changes (probably in separate prs)

you can have a look here: https://github.com/hpi-schul-cloud/tldraw-server/tree/BC-7674

**Comment by dmonad** [comment]
Both projects are now owned by Redis. I suspect that ioredis will eventually phase out of existence, so I want to stick with node-redis for now.

I hear that node-redis has a branch / beta release that supports sentinel. So support will land eventually.

**Comment by Loki-Afro** [comment]
@dmonad true, we think that as well, but it took them ages, and based on that speed it will take even longer ;)
