### ISSUE TITLE
Prepare a demo for y-redis

### ISSUE THREAD

**Issue by dmonad** [yjs/y-redis#3]

**Comment by bionicles** [comment]
I'd use it! just some basic usage example would be clutch

**Comment by dmonad** [comment]
Hi @bionicles , thanks for your interest! Just a heads up: Unfortunately, I currently don't have time to work on it. If you are willing to, I'd be happy to help you out if you contribute to this repository.

**Comment by bionicles** [comment]
sure, I love me some Redis, and CRDTs are fascinating.

Question:

```
  const redis = new Redis()
  await redis.flushall()
  {
    const redisPersistence = new RedisPersistence()
```

how does RedisPersistence find out about Redis?

**Comment by rchrd2** [comment]
An example in the README on how to use and configure this would be very helpful.

**Comment by ahoyahoy** [comment]
+1
please!

**Comment by datzun** [comment]
+1

**Comment by appletea233** [comment]
plz +1

**Comment by petru-planable** [comment]
+1

**Comment by sdzhu** [comment]
in your y-websocket repo, modify bin/utils.js like this
//use y-redis
const redisConfig = {
  host: process.env.REDIS_HOST,
  port: process.env.REDIS_PORT,
  password: process.env.REDIS_PASSWORD,
  db: process.env.REDIS_DB,
  keyPrefix: process.env.REDIS_KEY_PREFIIX
}

const ldb = new RedisPersistence({redisOpts: redisConfig})
persistence = {
  provider: ldb,
  bindState: async (docName, ydoc) => {
    ldb.bindState(docName, ydoc)
  },
  writeState: async (docName, ydoc) => {}
}

**Comment by TannerW** [comment]
Any updates on this?

**Comment by manurampandit** [comment]
Hi @dmonad - I'm interested to work on creating a readme for how to use this as anyways I need to use this for setting this up in a websocket server. In case you have some references on how `y-redis` was used across any project, it would be quite helpful.

**Comment by orangejava** [comment]
> You set the address as a parameter of the RedisPersistence (the default is localhost)

Hello, @dmonad. I use yjs in my project, and use y-websocket to transfer data, now I want to use y-redis to store the data, I try to use y-redis in the initialization of setupWSConnection, but it not work and the redis data cannot update to document. So could you update the readme for how to use in y-websocket or how to use y-redis correctly? Thanks.

**Comment by chung-nh** [comment]
> in your y-websocket repo, modify bin/utils.js like this //use y-redis const redisConfig = { host: process.env.REDIS_HOST, port: process.env.REDIS_PORT, password: process.env.REDIS_PASSWORD, db: process.env.REDIS_DB, keyPrefix: process.env.REDIS_KEY_PREFIIX }
> 
> const rp = new RedisPersistence({redisOpts: redisConfig}) persistence = { provider: rp, bindState: async (docName, ydoc) => { rp.closeDoc(docName) return rp.bindState(docName, ydoc) }, writeState: async (docName, ydoc) => {} }

Do you know how to config for awareness?
